### ISSUE TITLE
slpLMSnet - p's do not sum to one with multiple outcomes?

### ISSUE THREAD

**Issue by ajwills72** [ajwills72/catlearn#5]
Ivan Ivanchei reports (email) that when using slpLMSnet as a multi-outcome networks, the response probability vector (p) does not sum to one ... which it probably should?

**Comment by lenarddome** [comment]
Thanks for letting me know. 

I believe it is a problem with the documentation, as the logistic choice function should work almost exactly as `act2probrat()`. The documentation should say that it **outputs ratings of outcome probabilities**.

Currently, `slpLMSnet` only includes Equation 7 from Gluck and Bower (1988):

![Screenshot 2021-12-16 at 10-43-08 227_1 tif - GluckBower1988 pdf](https://user-images.githubusercontent.com/23503601/146362319-65561640-e56b-491f-8ff8-0eebdc4dd07b.png)

So I think the solution is for me to:

1. update the function to include a ratio response rule.
2. update the documentation.

**Comment by ajwills72** [comment]
Ah, good point. Yes, that seems to be the way to go :-)
